project_urls:
  Project Site: https://jhnnsrs.github.io/doks/
  Report Issues: https://github.com/jhnnsrs/mikro-napari/issues
  Documentation: https://jhnnsrs.github.io/doks/
  User Support: https://jhnnsrs.github.io/doks/
  Twitter: https://twitter.com/jhnnsrs
